[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
axum = { workspace = true, features = ["macros", "ws"] }
better_tokio_select = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "chrono", "runtime-tokio"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true }
tokio-stream = { workspace = true, features = ["sync"] }
tower-http = { workspace = true, features = ["cors", "fs"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
utoipa-redoc = { workspace = true, features = ["axum"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
futures-util = { workspace = true }
dotenvy = { workspace = true }
