[package]
name = "vk-video-live"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["net", "macros", "rt", "rt-multi-thread"] }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }

[lints]
workspace = true
